apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-test-server
  namespace: auto-test
  labels:
    app: auto-test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-test-server
  template:
    metadata:
      labels:
        app: auto-test-server
    spec:
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: auto-test-certs
          secret:
            secretName: auto-test-certs
      containers:
        - name: auto-server
          imagePullPolicy: Never
          image: registry.cn-hangzhou.aliyuncs.com/litiewang/litiewang:20210111155855
          command: ["java","-jar","-Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005","-Duser.timezone=GMT+8","-Dspring.profiles.active=prod","app.jar"]
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_SERVICE_HOST
              value: '192.168.1.122'
            - name: MYSQL_SERVICE_PORT
              value: '3306'
            - name: USER_NAME
              value: 'root'
            - name: PASSWORD
              value: 'zea0i+6hx7Dp'
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/test/probe
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: auto-test-certs
              mountPath: /certs

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: auto-test-server-service
#  namespace: auto-test
#  labels:
#    app: auto-test-server
#spec:
#  type: NodePort
#  ports:
#    - name: http
#      port: 80
#      nodePort: 31000
#  selector:
#    app: auto-test-server
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  labels:
#    k8s-app: auto-test
#  name: auto-test-certs
#  namespace: auto-test
#type: Opaque