
kube:
  debugger: true
  manyEnv: false
  repository:
    basePath: "/app/"
server:
  port: 8890
  servlet:
    context-path: /api
  # 解决Tomcat问题
  tomcat:
    max-http-header-size: 10240000
    max-http-post-size: 10240000
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml   # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: com.auto.test.entity  # 注意：对应实体类的路径
  #开启驼峰转换
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #启动时加载
  mvc:
    servlet:
      load-on-startup: 0
  # 上传文件限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
swagger:
  enable: false #是否禁用swagger
logging:
  level:
    com:
      rabbit:
        dao : debug
  config: classpath:logback-admin.xml


#token过期时间设置
token:
  expire:
    seconds: 86400 # token过期时间，24个小时
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)


log:
  level:
    #日志级别从低到高分为：
    #  配置TRACE < DEBUG < INFO < WARN < ERROR < FATAL
    root: INFO
    my: DEBUG
  file: logs/admin-server.log
  maxsize: 10MB