apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-demo01
  namespace: k8s-manager
spec:
  schedule: "0 0 12 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello
              image: busybox