apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-demo01
  namespace: default
spec:
  schedule: "0 0 12 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cronjob
              image: registry.cn-hangzhou.aliyuncs.com/litiewang/litiewang:20210111154534
              command: ["java","-jar","-Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005","-Duser.timezone=Asia/Jerusalem","-Dspring.profiles.active=prod","app.jar"]
              args:
              env:
                - name: MYSQL_SERVICE_HOST
                  value: '192.168.1.122'
                - name: MYSQL_SERVICE_PORT
                  value: '3306'
                - name: USER_NAME
                  value: 'root'
                - name: PASSWORD
                  value: 'zea0i+6hx7Dp'
              livenessProbe:
                httpGet:
                  scheme: HTTP
                  path: /api/test/probe
                  port: 8800
                initialDelaySeconds: 30
                timeoutSeconds: 30